// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CV.Lottery.Models;

public partial class LotteryUsers
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string UserId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public bool? IsActive { get; set; }

    public string UserName { get; set; }

    public virtual ICollection<Payments> Payments { get; set; } = new List<Payments>();

    public virtual AspNetUsers User { get; set; }

    public virtual ICollection<Winner> Winner { get; set; } = new List<Winner>();
}