// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CV.Lottery.Models;

public partial class LuckyDrawMaster
{
    public int Id { get; set; }

    public DateTime? EventDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public bool? IsActive { get; set; }

    public string EventName { get; set; }

    public decimal? Amount { get; set; }
}