// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CV.Lottery.Models;

public partial class Payments
{
    public int PaymentId { get; set; }

    public int UsersId { get; set; }

    public string Transaction { get; set; }

    public string PaymentStatus { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public bool? IsActive { get; set; }

    public virtual LotteryUsers Users { get; set; }
}